# Generated by Django 3.1.1 on 2020-09-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200906_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationforleave',
            name='application_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
