# Generated by Django 3.1.1 on 2020-09-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_applicationforleave_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leave_pending',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
