# Generated by Django 3.1.1 on 2020-09-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_leave_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationforleave',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
