# Generated by Django 3.1.1 on 2020-09-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_applicationforleave_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationforleave',
            name='leave_pending',
        ),
    ]
